
name: CMake Build

env:
  CMAKE_VERSION: 3.20.1
  BUILD_TYPE: Debug

on:
  push:
    branches: [cmake-build]

  pull_request:
    branches: [master]

jobs:
  build-ubuntu:
    name: Ubuntu bundled build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install conan
      run: python3 -m pip install conan

    - name: Build
      run: |
        mkdir build
        cd build
        conan install .. --build missing
        cmake ..
        cmake --build . -j8

        #- name: Verification
        #  run: |
        #    cd ./EXAMPLES/verification/ && ../../build/OpenSeesTcl runVerificationSuite.tcl
    - name: Build OpenSeesPy
      run: |
        cd ./build
        cmake ..
        make -j 4
        make OpenSeesPy
        mkdir fake_folder
        ls
        cd lib
        ls
    - name: Rename OpenSeesPy
      run: |
        cd ./build
        ls
        cd lib
        ls
        cd ..
        mv lib/OpenSeesPy.so lib/opensees.so

# Simple sanity test
    - name: Verification OpenSeesPySP
      run: |
        export PYTHONPATH="${PYTHONPATH}:./build/lib/"
        python ../examples_py/example_variable_analysis.py
#        # Simple MP sanity test
#        - name: Verification OpenSeesPyMP
#          run: |
#            mpiexec -np 2 python ../examples_py/example_mpi_paralleltruss_explicit.py

# Not building on Windows until we can figure out how to use Fortran
# with Github Actions
    #  build-win32:
    #    name: Build on Windows
    #    runs-on: [windows-latest]
    #    steps:
    #    - name: Checkout sources
    #      uses: actions/checkout@v2
    #      with: {ref: cmake-build}
    #    
    #    - name: Install Conan
    #      uses: turtlebrowser/get-conan@main
    #
    #    - name: Build
    #      run: |
    #        mkdir build
    #        cd build
    #        cmake ..
    #        cmake --build . --target OpenSeesTcl -j5


