name: CMake Build

env:
  CMAKE_VERSION: 3.20.1
  BUILD_TYPE: Debug
on:
  push:
    branches: [cmake-build]
jobs:
  build:
    name: Ubuntu Build
    runs-on: ubuntu-latest
    steps:
    - run: |
        git checkout cmake-build
        mkdir build
        cd build
        cmake ..
        cmake --build . --target OpenSeesTcl

